### ISSUE TITLE
domain without www is 404

### ISSUE THREAD

**Issue by adamhk0** [sentora/sentora-core#144] opened 2015-04-01 02:13 UTC
http://forums.sentora.org/showthread.php?tid=1353

After I changed @ to mydomain.com in CName record at Sentora DNS Manger.
The website show up properly.

Before
Host Name:www
Target: @ 
After
Host Name:www
Target: mydomain.com

Still don't know why.
some of my sites don't have this problem

**Comment by Caffe1neAdd1ct** [comment] 2015-09-28 11:41
`@` should work to reference the domain...

Could you check the zone file is being generated correctly when you use the `@` reference?

`vi /etc/sentora/configs/bind/zones/domain.com.txt`

For example I have:

`@               3600            IN              A               000.000.000.000`

and a CNAME of:

`www             3600            IN              CNAME           @`

If it hasn't changed yet force a re-run of the daemon.php then check again.

**Comment by Dukecitysolutions** [comment] 2023-03-18 06:01
Can't reproduce in v2. All works as intended. Closing for now.

**Closed by Dukecitysolutions** 2023-03-18 06:01 UTC
Labels: bug
