### ISSUE TITLE
[Ubuntu 14.04 LTS-Installer]

### ISSUE THREAD

**Issue by michal-sapsa** [sentora/sentora-core#185] opened 2015-07-14 17:45 UTC
On a minimal Ubuntu install there are few problems that still aren't fixed.
Before installing MySQL:
```  installers/zip/1.0.0 [108207] -> "sentora_preconfig.zip" [1]```
```chattr: Operation not supported podczas odczytu flag /etc/resolv.conf```
In middle of Postfix
```/etc/aliases does not exist, creating it.```
```WARNING: /etc/aliases exists, but does not have a root alias.```
```ERROR 1071 (42000) at line 115: Specified key was too long; max key length is 1000 bytes```

The last error was issued 5months ago, when Mr.B promised "quick-fix" : http://forums.sentora.org/showthread.php?tid=1134&page=4 It was in CentOS then, and its still there even on Ubuntu.

Any estimation time for update or is it dead-from-begining ?

**Comment by eka7a** [comment] 2015-07-27 01:40
We encounter a similar error.

OS: CentOS 7.1.x 64bit

-- Installing Postfix
Package 2:postfix-2.10.1-6.el7.x86_64 already installed and latest version
ERROR 1071 (42000) at line 115: Specified key was too long; max key length is 1000 bytes

**Comment by TGates71** [comment] 2015-07-27 15:39
@MBlagui

**Comment by MBlagui** [comment] 2015-07-27 21:25
chattr on ubuntu is not an issue.

@TGates71 you accepted the patch but I had other pulls waiting as preconf need to be patched too and tagged as 1.0.1 and installer updated that would fix centos 7 issue for ever.

Ubuntu 14 I will try to check the error but it's minimal unlike centos 7 that have 2 tables missing in install. Postfix vacation.

Centos 7 error is caused by a table that we don't EVEN NEED that's the mad part. I cleaned up postfix SQL and will in feature offer hidden gems.

**Comment by hardlick** [comment] 2015-07-27 21:30
On ubuntu 15.04 all works fine!, with  this pull request.

**Comment by MBlagui** [comment] 2015-07-28 15:04
Sorry @hardlick we didn't test 15.04 we focus on LTS releases currently but I will take notice over this and check it later once we finish the installer 1.0.2 release.

**Comment by Caffe1neAdd1ct** [comment] 2015-09-28 10:49
Seen this has been added to the installers now, closing. Please open a new issue if problems still arise.

**Closed by Caffe1neAdd1ct** 2015-09-28 10:49 UTC
