### ISSUE TITLE
Qoutas are not working when creating packages

### ISSUE THREAD

**Issue by NigelNapier** [sentora/sentora-core#281] opened 2016-11-16 02:41 UTC
Operating System: Ubuntu

Operating System Version number: 14.04 LTS

Sentora Version: 1.0.4

Issue: i've tried creating a package with qoutas and I get the error in the picture.

![package_error](https://cloud.githubusercontent.com/assets/1205726/20332778/3414993a-ac13-11e6-9116-46e2c859abe6.png)

**Comment by PS2Guy** [comment] 2017-07-11 18:28
@TGates71, I'm certain this is the same bug as #300

**Comment by TGates71** [comment] 2017-07-11 18:59
Works fine for me... hmm.. Used quotas of 5 for all and 500 for BW and HD
![package_creation](https://user-images.githubusercontent.com/2555611/28085324-675fbd06-6649-11e7-8dab-2d5ce592d755.png)

**Comment by TGates71** [comment] 2017-07-11 19:06
Did not notice any differences, anything in the error logs?

**Comment by MBlagui** [comment] 2017-07-18 08:11
@PS2Guy did you mean sentora 1.0.3 as 1.0.4 is in current release? Or are you using the master?

Thanks for the feedback but we are freezing the current master and preparing for 1.0.4 release so if you can help understand better the bug so we can push the fix quickly. 

Also are you using ubuntu server or ubuntu desktop like in #300

**Comment by Dukecitysolutions** [comment] 2023-03-18 04:26
Can't reproduce the issue in V2. Closing for now.

**Closed by Dukecitysolutions** 2023-03-18 04:26 UTC
Labels: Need more checks
