### ISSUE TITLE
Unwanted domain restriction

### ISSUE THREAD

**Issue by mbcx2** [sentora/sentora-core#103] opened 2015-01-28 11:39 UTC
Hello, there is an unwanted restriction which does not allow a registered sub-domain as a domain of the server.

**Comment by trojanspike** [comment] 2015-01-28 11:41
Put in the domain first then the sub-domain even if the main domain isn't routed to your ip

**Comment by bobsta63** [comment] 2015-01-28 13:23
Yes @trojanspike is correct, you must first add the top level domain before being able to then add the sub-domain, we've done it like this for various reasons. I'll close this as it is not a bug but the way in which it is designed.

To be clear, you don't need to host anything on the top-level domain but it must be present on your account (mainly for security reasons, eg others on the server can't then add and hi-jack other sub-domains under that domain)

**Closed by bobsta63** 2015-01-28 13:23 UTC

**Comment by mbcx2** [comment] 2015-01-29 05:53
Hello, I tried to do that, but if I create another account and try to add the domain, it will say it has been added on another account.
Is it possible to add it directly to domains or dns?
