### ISSUE TITLE
View hosting without domain.

### ISSUE THREAD

**Issue by QuakeMediaUK** [sentora/sentora-core#104] opened 2015-01-28 13:06 UTC
Would it be possible to add something to view the files on a hosting account via a browser without having to use a domain. For example, with cPanel, you can access node.example.org/~username
and it will show the Files on the hosting for that account.
If you could, that would be great.

**Comment by bobsta63** [comment] 2015-01-28 13:24
Added as a feature request - will look to implement in future.

**Comment by QuakeMediaUK** [comment] 2015-01-28 13:27
Thanks :)

**Comment by bobsta63** [comment] 2015-01-28 16:35
No problem :)

**Comment by TGates71** [comment] 2015-01-28 18:05
Basically this is the DNS-less preview.
```# Add Alias for DNS-Less Previews
<VirtualHost *:80>
ServerName xxx.xxx.xxx.xxx
DocumentRoot c:/zpanel/panel/
AliasMatch ^/~([a-zA-Z0-9]+)/?(.*) c:/zpanel/hostdata/$1/public_html/$2
<Directory c:/zpanel/hostdata>
Options FollowSymLinks Indexes
AllowOverride All
Order Allow,Deny
Allow from all
DirectoryIndex index.php
    <IfModule mod_php5.c>
        AddType application/x-httpd-php .php
        php_flag magic_quotes_gpc Off
        php_flag track_vars On
        php_flag register_globals Off
        php_admin_value upload_tmp_dir c:/zpanel/temp
    </IfModule>
</Directory>
```
Need to replace xxx.xxx.xxx.xxx with your server's public IP and may need to update the paths for your OS (Current paths are for Windows)
You enter this as a Global ZPanel/Sentora Entry in Module Admin>Apache Admin

**Comment by QuakeMediaUK** [comment] 2015-01-28 18:41
Added to Global Sentora on CentOS and has appeared to stop Apache from starting.

**Comment by bobsta63** [comment] 2015-01-28 18:44
Did you update the paths ;) - If Apache isn't working check the Apache error logs on your server, it should help pinpoint what the problem is bud.

**Comment by QuakeMediaUK** [comment] 2015-01-28 18:45
Yes, I updated the paths and IP to match that of the server and CentOS.
Tried removing the entry manually and currently restarting server

**Comment by QuakeMediaUK** [comment] 2015-01-28 18:49
Error log, looks to be the fault:
[Sun Jan 25 18:15:49.607798 2015] [core:notice] [pid 4608] AH00052: child pid 5336 exit signal Segmentation fault (11)
[Sun Jan 25 18:16:02.231062 2015] [mpm_prefork:notice] [pid 4608] AH00170: caught SIGWINCH, shutting down gracefully

**Comment by QuakeMediaUK** [comment] 2015-01-28 19:10
Ok... Anyone know how to fix the vhosts file? ;)

**Comment by QuakeMediaUK** [comment] 2015-01-28 19:43
This doesn't work for CentOS and will stop Apache from starting.

**Comment by bobsta63** [comment] 2015-01-28 19:50
How come you close it? - Did you not want me to implement this feature in future? (so you can easily enable and it be supported in the panel?)

@TGates71 gave you the example as a quick work around for now :)

**Comment by QuakeMediaUK** [comment] 2015-01-28 20:01
Yes, sorry. Def want it adding. Must have clicked the wrong button.

**Comment by TGates71** [comment] 2015-01-28 22:59
This works on ALL OS that run apache. You must not have updated the paths properly.
OOPS! recheck the addition above, I forgot to add </virtualhost> at the beginning as I just copy/pasted right from my settings.

**Comment by jd1pinoy** [comment] 2015-01-29 01:39
AFAIK this can be added in CentOS "/etc/sentora/configs/apache/httpd.conf" file
and add this line: AliasMatch ^/~([a-zA-Z0-9]+)/?(.*) /var/sentora/hostdata/$1/public_html/$2

example httpd.conf:
# Sentora Apache Include file
# Written by Bobby Allen, 15/05/2011

# Set the Sentora Alias (used for development, sable will eventually use a VHOST)
#Alias /Sentora /etc/sentora/panel

# Set a default server name for the master configuration to supress Apache daemon warnings
ServerName localhost
AliasMatch ^/~([a-zA-Z0-9]+)/?(.*) /var/sentora/hostdata/$1/public_html/$2 #<-- add it to this line
# Setup the directory settings and PHP security flags for the Sentora application directory.
<Directory /etc/sentora/panel>
    Options +FollowSymLinks
    DirectoryIndex index.php
    <IfModule mod_php5.c>
        AddType application/x-httpd-php .php
        php_flag magic_quotes_gpc Off
        php_flag track_vars On
        php_flag register_globals Off
        php_admin_value upload_tmp_dir /var/sentora/temp
    </IfModule>
</Directory>

Yeah make sure to use correct path.

I tried adding AliasMatch in Global Sentora Entry but it doesn't work.

**Comment by dssilva** [comment] 2015-09-17 13:01
Hi,

When I try the method above the error 403 Forbidden is showed. What I did wrong?

**Comment by drjaydenm** [comment] 2015-10-21 23:39
@dssilva, I have gotten this to work on Ubuntu 14.04. Using @jd1pinoy solution of modifying the "/etc/sentora/configs/apache/httpd.conf" file.
Edit the "/etc/sentora/configs/apache/httpd.conf" file and add the following lines:
```
AliasMatch ^/~([a-zA-Z0-9]+)/?(.*) /var/sentora/hostdata/$1/public_html/$2

# Setup folder permissions for DNS-less sites
<Directory /var/sentora/hostdata>
    Options FollowSymLinks
    AllowOverride All
    Order Allow,Deny
    Allow from all
    Require all granted
    DirectoryIndex index.html index.htm index.php index.asp index.aspx index.jsp index.jspa index.shtml index.shtm
    <IfModule mod_php5.c>
        AddType application/x-httpd-php .php
        php_flag magic_quotes_gpc Off
        php_flag track_vars On
        php_flag register_globals Off 
        php_admin_value upload_tmp_dir /var/sentora/temp
    </IfModule>
</Directory>
```
The start of the modified file should now look something like this:
```
# Sentora Apache Include file
# Written by Bobby Allen, 15/05/2011

# Set the Sentora Alias (used for development, sable will eventually use a VHOST)
#Alias /Sentora /etc/sentora/panel

# Set a default server name for the master configuration to supress Apache daemon warnings
ServerName localhost
AliasMatch ^/~([a-zA-Z0-9]+)/?(.*) /var/sentora/hostdata/$1/public_html/$2

# Setup folder permissions for DNS-less sites
<Directory /var/sentora/hostdata>
    Options FollowSymLinks
    AllowOverride All
    Order Allow,Deny
    Allow from all
    Require all granted
    DirectoryIndex index.html index.htm index.php index.asp index.aspx index.jsp index.jspa index.shtml index.shtm
    <IfModule mod_php5.c>
        AddType application/x-httpd-php .php
        php_flag magic_quotes_gpc Off
        php_flag track_vars On
        php_flag register_globals Off 
        php_admin_value upload_tmp_dir /var/sentora/temp
    </IfModule>
</Directory>

# Setup the directory settings and PHP security flags for the Sentora application directory.
<Directory /etc/sentora/panel>
    Options +FollowSymLinks
    DirectoryIndex index.php
    <IfModule mod_php5.c>
        AddType application/x-httpd-php .php
        php_flag magic_quotes_gpc Off
        php_flag track_vars On
        php_flag register_globals Off
        php_admin_value upload_tmp_dir /var/sentora/temp
    </IfModule>
</Directory>
```
The key to fixing the 403 Forbidden errors seemed to be the **Require all granted** rule.

**Comment by TGates71** [comment] 2015-10-22 16:42
Correct about the Require all granted.
But you should NOT be editing the httpd.conf file rather add it as a Global Sentora Entry in Admin > Module Admin > Apache Config > Global Sentora Entry.

**Comment by drjaydenm** [comment] 2015-10-22 19:47
I couldn't seem to get it to work correctly by placing the rules in the settings, it seemed to be ignored. Have you got any tips to get it working correctly?

**Comment by drjaydenm** [comment] 2015-10-23 01:07
Just an update, I have managed to get this all working using the Global Sentora Entry in the Apache Settings in Sentora. All I needed to do was escape out of the VHost rule that Sentora places the content of the Global Sentora Entry into.

Following @TGates71 instructions, go to: Admin > Module Admin > Apache Config, and then add the following to the Global Sentora Entry field:
```
# Escape out of VHost config
</VirtualHost>

# Set the Sentora Alias (used for development, stable will eventually use a VHOST)
AliasMatch ^/~([a-zA-Z0-9]+)/?(.*) /var/sentora/hostdata/$1/public_html/$2

# Setup folder permissions for DNS-less sites
<Directory /var/sentora/hostdata>
    Options FollowSymLinks
    AllowOverride All
    Order Allow,Deny
    Allow from all
    Require all granted
    DirectoryIndex index.html index.htm index.php index.asp index.aspx index.jsp index.jspa index.shtml index.shtm
    <IfModule mod_php5.c>
        AddType application/x-httpd-php .php
        php_flag magic_quotes_gpc Off
        php_flag track_vars On
        php_flag register_globals Off 
        php_admin_value upload_tmp_dir /var/sentora/temp
    </IfModule>
</Directory>

# Enter back into the VHost config
<VirtualHost *:80>
```

Once the daemon runs, and apache is restarted, this should work correctly and you should be able to access sites through a link like the following http://DOMAIN_NAME/~zadmin/SITE_FOLDER_NAME/

**Comment by Guillermonnn** [comment] 2015-11-14 18:22
Hello

My SO is Centos6...
I am an amateur in hosting, and I've followed all the steps of drjaydenm, not work for me ....

I forgot something ??
That I can do differently ???

Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator, zadmin@localhost and inform them of the time the error occurred, and anything you might have done that may have caused the error.
More information about this error may be available in the server error log.
Apache Server at 10.9.53.203 Port 80


Thank you
greetings from Spain and sorry for my English

**Comment by erm3nda** [comment] 2016-01-11 08:14
I tried and get a Forbidden. Shoul I change anything else?

**Comment by kemboidickson** [comment] 2016-08-03 08:19
It works good, can I remove the "~zadmin" part?

**Comment by TGates71** [comment] 2016-08-03 18:26
What do you mean? That us how you view the hosted pages with out a domain. ~[username]

**Comment by PremiumScript** [comment] 2018-11-13 08:35
> Just an update, I have managed to get this all working using the Global Sentora Entry in the Apache Settings in Sentora. All I needed to do was escape out of the VHost rule that Sentora places the content of the Global Sentora Entry into.
> 
> Following @TGates71 instructions, go to: Admin > Module Admin > Apache Config, and then add the following to the Global Sentora Entry field:
> 
> ```
> # Escape out of VHost config
> </VirtualHost>
> 
> # Set the Sentora Alias (used for development, stable will eventually use a VHOST)
> AliasMatch ^/~([a-zA-Z0-9]+)/?(.*) /var/sentora/hostdata/$1/public_html/$2
> 
> # Setup folder permissions for DNS-less sites
> <Directory /var/sentora/hostdata>
>     Options FollowSymLinks
>     AllowOverride All
>     Order Allow,Deny
>     Allow from all
>     Require all granted
>     DirectoryIndex index.html index.htm index.php index.asp index.aspx index.jsp index.jspa index.shtml index.shtm
>     <IfModule mod_php5.c>
>         AddType application/x-httpd-php .php
>         php_flag magic_quotes_gpc Off
>         php_flag track_vars On
>         php_flag register_globals Off 
>         php_admin_value upload_tmp_dir /var/sentora/temp
>     </IfModule>
> </Directory>
> 
> # Enter back into the VHost config
> <VirtualHost *:80>
> ```
> Once the daemon runs, and apache is restarted, this should work correctly and you should be able to access sites through a link like the following http://DOMAIN_NAME/~zadmin/SITE_FOLDER_NAME/

hi there

followed your guide, may access to TXT files, but error 500 with PHP files

**Closed** 2019-04-21 01:51 UTC
Labels: feature
