### ISSUE TITLE
Error with sub-domain

### ISSUE THREAD

**Issue by wings40** [sentora/sentora-core#246] opened 2016-02-20 00:10 UTC
Hello, when I try to add a sub-domain occurs an error:
Your Domain name is not valid. Please enter a valid Domain Name: i.e. 'domain.com'
And and it's not possible create an email-box (The selected domain was not valid.) 

![screenshot_2](https://cloud.githubusercontent.com/assets/17347104/13192637/f024f51c-d74c-11e5-897a-9cdc03e88211.jpg)
![screenshot_1](https://cloud.githubusercontent.com/assets/17347104/13192636/f024a6f2-d74c-11e5-9f23-fe1778875a4a.jpg)

Thanks, 

Augusto

**Comment by CasteyDaSilva** [comment] 2016-02-20 01:01
I've the same problem with .org domains. Temporary solution is add subdomain as domain.

**Comment by eByte23** [comment] 2016-02-20 02:35
@wings40, have you got the latest version of the repo? If not I'd try copying the subdomain module folder from the src here and putting into your site to see if that works.

**Comment by wings40** [comment] 2016-02-20 03:42
@eByte23, I suppose yes, I install it with this command line: bash <(curl -L -Ss http://sentora.org/install)

**Comment by TGates71** [comment] 2016-02-20 03:56
What OS are you using? What Sentora version (1.0.0 or 1.0.3)? Are you using the zadmin account or a user account?

**Comment by wings40** [comment] 2016-02-20 04:01
I'm using Ubuntu 14.04 and Sentora version is 1.0.3. 
I'm using zadmin account.

**Comment by TGates71** [comment] 2016-02-20 04:02
I just tested adding the exact domain and sub domain you entered above and it worked just fine. (Ubuntu 14.04/Sentora 1.0.3)

**Comment by TGates71** [comment] 2016-02-20 04:18
Are all the files and folders in /etc/sentora/ owned by apache? (www-data) And set to 755?

**Comment by wings40** [comment] 2016-02-20 04:32
All the files and folders are in the default way. The script installer do everything.

**Comment by eByte23** [comment] 2016-02-20 05:17
@wings40 I'd assume that I'd you copied the module it will work or if you do a diff there will be changes to the file

**Comment by MBlagui** [comment] 2016-02-20 12:04
For me it's a bug.

It's related how we check if subdomain is valid. It should only look if it's sub.EXISTINGDOMAIN. not check how many dots we have in it. 

I need to check back the routine.

**Comment by AldemaroC** [comment] 2016-02-20 16:01
Is there any workaround? The TLD .com.br do not work too.

**Comment by CasteyDaSilva** [comment] 2016-02-20 19:54
@AldemaroC yes, u can add subdomain as domain.

**Comment by MBlagui** [comment] 2016-02-21 00:49
issue is here:

https://github.com/sentora/sentora-core/blob/master/modules/sub_domains/code/controller.ext.php

I think IsValidDomainName() regex there need to be modified.

**Comment by AldemaroC** [comment] 2016-02-21 12:50
How does sentora check if a domain is valid? I'd be glad to fix it and pull to github. I can't even create mailbox for my domains (even if there is only one dot).
![image](https://cloud.githubusercontent.com/assets/6959146/13202642/79b73fa4-d880-11e5-9fc2-71f5efe1abcb.png)

**Comment by MBlagui** [comment] 2016-02-21 18:41
Used the same domain. Able to create mailbox. This is not an issue I'm currently trying to track.

Not a bug using domain.cu.cc. Please use the forum if you still face the issue.

http://forums.sentora.org/

Closing this issue.

M B

**Closed by MBlagui** 2016-02-21 18:41 UTC
Labels: invalid
