### ISSUE TITLE
Word Press Duplicator broke Sentora database 

### ISSUE THREAD

**Issue by bbloldd** [sentora/sentora-core#195] opened 2015-08-06 05:12 UTC
After migrating my Word Press backup to Sentora using FTP account, my WordPress and Sentora database connection has broken completely. 

My WordPress site backup was done by Duplicator plungin and its paths and permissions seems having conflicts with Sentora DB configuration.   

This seems critical issue as I can not even login to my Sentora account or even see the login screen. 

![sentoradb](https://cloud.githubusercontent.com/assets/11577979/9104265/002a48ec-3bbf-11e5-9155-770bc62ace29.png)

My WP version is 4.1 and Duplicator version 0.5.12

What happened chronically is as follow.

My ftp account was created on domain home directory. 

After having some difficulties to access to ftp I could connect to my domain ftp account with WinSCP but ended up with this error message. 

Server sent passive reply with unroutable address xXX.xX.xX.XX(My server private IP), using host address instead.

Timeout detected. (data connection)
Could not retrieve directory listing
Error listing directory '/'. 

This could be Amazon AWS instance problem but Sentora also updates and maintain a lot different path and directory permission form regular Linux.  This might be also Sentora issue.

I have also tried to test it from https://ftptest.net/  and got this result.

Error: Server returned unroutable private IP address in PASV reply
Make sure the server is configured to allow passive mode connections.
If the server is behind a NAT router, make sure the server knows its external IP address.
The range of ports used for passive mode must be opened in all involved firewalls.
The range of ports used for passive mode must be forwarded by all involved NAT routers.
Try uninstalling all firewalls and plug your computer directly into your modem, thus bypassing the router.
This might be my WinSCP Setting problem but don't what..

I tried to use FilleZilla and did not work. 

Somehow it worked on FilleZilla.

I only changed 

FilleZilla Edit menu, Preference, FTP, Active mode , deselect "Don't use external IP for internal ...(D)"

After my WordPresss installation, it did not work anymore ...

Error: Connection got closed prematurely

from https://ftptest.net

And newly migrated WP site has database connection problem as well.

Error establishing a database connection

and suddenly Sentora access is also impossible. 

![sentoradb](https://cloud.githubusercontent.com/assets/11577979/9104265/002a48ec-3bbf-11e5-9155-770bc62ace29.png)

Is this specific enough?

**Comment by 5050** [comment] 2015-08-06 05:39
I do not understand how it can be some conflict between two differents databases, except if you backup not only WP but also sentora databases.
At my idea it is not a problem from Sentora but from Duplicator of fdrom the use of it you did.
Please provide more precises information about backup content, about error message, etc. With only your description, it is not possible to try to reproduce your problem or to understand what happened.

**Comment by bbloldd** [comment] 2015-08-06 06:08
I wish Duplicator puglin can backup WP contents meaning psots, pages,
themes, plugins, data data and etc.
You ahve to create DB and DB users seperately when you restore.

You can learn more on duplicator here

https://wordpress.org/plugins/duplicator/


On Wed, Aug 5, 2015 at 10:39 PM, Pascal Peyremorte <notifications@github.com

**Comment by PhilipMcGaw** [comment] 2015-08-06 07:36
What database information does the plugin ask for? Do you feed it the root MySQL user and password for your server, or do you need to make a username and password for the to be installed site?

Are other MySQL applications taken off line after you use this plugin?

Have you asked for support from the plugin developer or are you saying its a panel problem?

**Comment by 5050** [comment] 2015-08-06 12:18
--- Please do not edit the first message to answer a question (no notification), but add a new response. Else nobody will be notifyed for new post and it make the whole discussion incomprehensible.

You have many differents problems :

1) About FTP, we must know where the server is hosted : at home, at hosting provider, etc. It looks like your server or its network is not configured correctly, but you may be sure that sentora do it right : else we would have be submerged or same requests.

2) about database import : you must ensure that Duplicator does not import the master admin password (user "root"). If it was changed, you have to setup the new password in file /etc/sentora/panel/cnf/db.php

Please note that both are not problems related to sentora itself, so I will close this report now. 
If you cannot solve these problems alone, please open a discussion in the forums at http://forums.sentora.org.

**Closed by 5050** 2015-08-06 12:18 UTC
